version: '1.0'
services:
  almacen-api:
    build: ./
    container_name: almacenAPI
    command: dotnet run
    ports:
      - "5000:80"
    volumes:
    # in linux
      #- "./db/:/root/db/"
      # in windows
      - "./db:/db"
  sqlite3:
    image: keinos/sqlite3:latest
    container_name: sqlite-almacen
    stdin_open: true
    tty: true
    volumes:
    # in linux
      #- "./db/:/root/db/"
      # in windows
      - "./db:/db"
    command: sqlite3 /db/Almacen.db
    ports:
      - '9000:9000' # expose ports - HOST:CONTAINER
    restart: unless-stopped
networks:
  default:
    name: nat
    external: true
