version: '1.0'
services:
  almacen-api:
    build: ./
    container_name: almacenAPI
    command: dotnet run
    ports:
      - "5000:80"
  sqlite3:
    image: keinos/sqlite3:latest
    container_name: sqlite-almacen
    command: sqlite3 /root/db/sample.db
    stdin_open: true
    tty: true
    volumes:
      - "./db/:/root/db/"
networks:
  default:
    name: nat
    external: true
